# Generated by Django 3.1.7 on 2021-04-23 22:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testtest', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testtest.rubric'),
        ),
    ]
