# Generated by Django 3.1.7 on 2021-04-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testapp.news', verbose_name='Новость'),
        ),
    ]
